### ISSUE TITLE
Build Fails with Extra

### ISSUE THREAD

**Issue by Miustone** [sony-sagamidev/vendor_sony_pdx215-extra#1]
FAILED: out/soong/build.ninja
cd "$(dirname "out/host/linux-x86/bin/soong_build")" && BUILDER="$PWD/$(basename "out/host/linux-x86/bin/soong_build")" && cd / && env -i  "$BUILDER"     --top "$TOP"     --soong_out "out/soong"     --out "out"     -o out/soong/build.ninja --globListDir build --globFile out/soong/globs-build.ninja -t -l out/.module_paths/Android.bp.list --available_env out/soong/soong.environment.available --used_env out/soong/soong.environment.used.build Android.bp
error: vendor/sony/extra/Android.bp:90:1: module "com.sony.device.jar" variant "android_common": module source path "vendor/sony/extra/sonyframework/framework/com.sony.device.jar" does not exist
error: vendor/sony/extra/Android.bp:96:1: module "com.sonyericsson.colorextraction_impl.jar" variant "android_common": module source path "vendor/sony/extra/sonyframework/framework/com.sonyericsson.colorextraction_impl.jar" does not exist
error: vendor/sony/extra/Android.bp:102:1: module "com.sonymobile.album.jar" variant "android_common": module source path "vendor/sony/extra/sonyframework/framework/com.sonymobile.album.jar" does not exist
error: vendor/sony/extra/Android.bp:108:1: module "com.sonymobile.album.internal.jar" variant "android_common": module source path "vendor/sony/extra/sonyframework/framework/com.sonymobile.album.internal.jar" does not exist
error: vendor/sony/extra/Android.bp:120:1: module "somc-ext-mmwdiapi.jar" variant "android_common": module source path "vendor/sony/extra/sonyframework/framework/somc-ext-mmwdiapi.jar" does not exist
error: vendor/sony/extra/Android.bp:83:1: module "com.sonyericsson.idd_impl.jar" variant "android_common": module source path "vendor/sony/extra/sonyframework/product/framework/com.sonyericsson.idd_impl.jar" does not exist
error: vendor/sony/extra/Android.bp:153:1: module "vendor.dolby.hardware.dms" variant "android_arm64_armv8-2a-dotprod_cortex-a76": module source path "vendor/sony/extra/dolby/vendor/etc/vintf/manifest/vendor.dolby.hardware.dms.xml" does not exist
error: vendor/sony/extra/Android.bp:153:1: module "vendor.dolby.hardware.dms" variant "android_arm64_armv8-2a-dotprod_cortex-a76": module source path "vendor/sony/extra/dolby/vendor/etc/vintf/manifest/vendor.dolby.hardware.dms.xml" does not exist
error: vendor/sony/extra/Android.bp:153:1: module "vendor.dolby.hardware.dms" variant "android_arm64_armv8-2a-dotprod_cortex-a76": module source path "vendor/sony/extra/dolby/vendor/etc/vintf/manifest/vendor.dolby.hardware.dms.xml" does not exist
error: vendor/sony/extra/Android.bp:153:1: module "vendor.dolby.hardware.dms" variant "android_arm64_armv8-2a-dotprod_cortex-a76": module source path "vendor/sony/extra/dolby/vendor/etc/vintf/manifest/vendor.dolby.hardware.dms.xml" does not exist
error: vendor/sony/extra/Android.bp:76:1: module "com.google.protobuf-2.3.0-dummy.jar" variant "android_common": module source path "vendor/sony/extra/sonyframework/product/framework/com.google.protobuf-2.3.0-dummy.jar" does not exist
error: vendor/sony/extra/Android.bp:114:1: module "com.sonymobile.home.resourceprovider.jar" variant "android_common": module source path "vendor/sony/extra/sonyframework/framework/com.sonymobile.home.resourceprovider.jar" does not exist
17:26:35 soong bootstrap failed with: exit status 1

Removing Extra for now to make Builds...

**Comment by saku-bruh** [comment]
extra can be removed. everything is still a WIP...
